# Generated by Django 5.0.4 on 2024-07-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
