# Generated by Django 5.0.4 on 2024-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customer_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='residence_address',
            field=models.CharField(max_length=100),
        ),
    ]
