# Generated by Django 5.0.7 on 2024-07-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customer_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document_number',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
