# Generated by Django 5.0.7 on 2024-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_person_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=10, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('observations', models.TextField()),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
